### ISSUE TITLE
Doesn't build with recent versions of 4store (1.1.3)

### ISSUE THREAD

**Issue by cajus** [wwaites/py4s#4]
It seems like some of the includes have been renamed (4s-datatypes.h, 4s-hash.h) and a couple of method signatures changed.
# python setup.py build

running build
running build_py
running build_ext
building '_py4s' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_LAQRS=1 -DHAVE_RASQAL_WORLD=1 -DUSE_AVAHI=1 -Isrc -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/rasqal -I/usr/include/raptor2 -I/usr/include/python2.6 -c _py4s.c -o build/temp.linux-i686-2.6/_py4s.o -std=gnu99
_py4s.c:158:30: error: common/datatypes.h: No such file or directory
_py4s.c:160:25: error: common/hash.h: No such file or directory
In file included from _py4s.c:163:
src/frontend/import.h:19: warning: function declaration isn't a prototype
_py4s.c: In function '__pyx_pf_5_py4s_7_Cursor___cinit__':
_py4s.c:2730: error: too few arguments to function 'fs_query_init'
_py4s.c: In function '__pyx_pf_5_py4s_7_Cursor_execute':
_py4s.c:3259: warning: passing argument 1 of 'raptor_new_uri' from incompatible pointer type
/usr/include/raptor2/raptor.h:1148: note: expected 'struct raptor_world *' but argument is of type 'unsigned char *'
_py4s.c:3259: error: too few arguments to function 'raptor_new_uri'
_py4s.c:3268: error: too few arguments to function 'fs_query_execute'
_py4s.c: In function '__pyx_pf_5_py4s_7_Cursor_update':
_py4s.c:4124: warning: passing argument 1 of 'fs_update' from incompatible pointer type
src/frontend/update.h:13: note: expected 'struct fs_query_state *' but argument is of type 'struct fsp_link *'
error: command 'gcc' failed with exit status 1
